FROM pejdd/pgbase:v1

RUN apt -y install wget
RUN mkdir /app
WORKDIR /app

COPY ./build/libs/springtest0-1.0.jar springtest0-1.0.jar
#RUN wget -O dd-java-agent.jar 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST'


EXPOSE 8082 5432
CMD java -jar springtest0-1.0.jar
